### ISSUE TITLE
No modification, but strange results

### ISSUE THREAD

**Issue by Nyohohoho** [Huangying-Zhan/DF-VO#13]
Thank you for your excellent work and kind sharing.

I tried to run your code.
I downloaded the code and pretrained models without any modification.
I only modified the path so that KITTI dataset on my machine can be accessed.

However, I got this kind of result...
![Screenshot 2020-09-24 201202](https://user-images.githubusercontent.com/58693232/94143589-a2572a80-fea2-11ea-8b84-062a686b724e.png)

I cannot figure out the reason.

**Comment by DanRos22** [comment]
It seems you face the same problem I had.
If you see a warning regarding ```torch.nn.functional.grid_sample``` function, you need to add the flag ```align_corners = True```
(4 times across this project), in order to get the original behavior.
This change is needed apparently because you use a newer pytorch version compared to this repo requirements (1.1.0), and according to pytorch documentation:
```The default behavior up to version 1.2.0 was ``align_corners = True``.
Since then, the default behavior has been changed to ``align_corners = False``,```
@Huangying-Zhan, Maybe you can update your code so any new user won't experience the same difficulty. Thanks!
And BTW, thanks for sharing this work. it's great!

**Comment by Huangying-Zhan** [comment]
@DanRos22 Thanks for pointing out the issue and the suggestion.
