### ISSUE TITLE
Training with new datasets

### ISSUE THREAD

**Issue by kylelindgren** [Huangying-Zhan/DF-VO#4]
Thank you for sharing the evaluation code and pretrained models. I am interested in training and evaluating your method on a new dataset; do you plan to release the training source code in the near future?

**Comment by Huangying-Zhan** [comment]
Hi @kylelindgren , as mentioned in the README, the current training code is mixed up with some other projects. I am cleaning and summarizing the code.
I do plan to release the training code but it may take some time since it will come with other projects as well.

Anyway, for depth network training (stereo), you can refer to monodepth2 at the moment: https://github.com/nianticlabs/monodepth2

For others (optical flow training and monocular depth training), I will let you know when it is released but don't expect it will be available within these two months. Sorry about that.

**Comment by kylelindgren** [comment]
Hi Huangying, thank you for the quick response and explanations. No worries about the release timing. I look forward to playing with your method when released.

**Comment by isht7** [comment]
@Huangying-Zhan is there any update about when the training code will be released? Thanks!

**Comment by Huangying-Zhan** [comment]
Please see the reply in #35
